import type { Metadata } from "next";
import Layout from "@/components/layout/Layout";
import { Provider } from "@/components/ui/provider";
import React from "react";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{
          fontFamily: "Roboto, Arial, -apple-system, BlinkMacSystemFont, sans-serif",
        }}
      >
        <Provider>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
